#!/bin/bash
#echo $1
. "/home/antonis/motion/mqtt.conf"
if [ -f "/home/antonis/motion/$1.conf" ]; then
	. "/home/antonis/motion/$1.conf"
	mosquitto_pub -h "$broker" -p "$port" -t "$mqtt_topic" -m '{"detection": "MOTION_DETECTED", "camera": "'$1'"}'
fi
